name: MkDocs Publish

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Build and deploy
        run: |
          poetry run mkdocs build --verbose
          poetry run mkdocs gh-deploy --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
